fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: check-ast
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev:  v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
      files: src/abnf
- repo: local
  hooks:
    - id: py-test-unit
      name: pytest-unit
      entry: pytest tests/ --ignore=tests/fuzz
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push]
