"""Replay every committed acceptance corpus under the active backend (issue #138).

Each ``corpus/<module>.json`` was generated by ``gen_corpus.py`` under the
pure-Python backend and contains only inputs that round-trip there.  Replaying
under whichever backend is active turns a normal ``pytest`` run (rust backend)
into a python/rust differential check, and doubles as a deterministic
regression corpus.  No Hypothesis dependency and no backend skip — a plain
replay.

Parametrized per ``(module, rule)`` (not per individual string) to keep pytest
collection light for a ~15k-case corpus; each case is asserted in a loop and
the failing input is reported.

Regenerate after grammar/walker changes::

    python tests/fuzz/gen_corpus.py <module>
"""

import importlib
import json
import pathlib

import pytest

CORPUS_DIR = pathlib.Path(__file__).parent / "corpus"


def _params() -> list:
    params = []
    for path in sorted(CORPUS_DIR.glob("*.json")):
        module_name = path.stem
        corpus: dict[str, list[str]] = json.loads(path.read_text(encoding="utf-8"))
        for rule_name, cases in corpus.items():
            params.append(
                pytest.param(
                    module_name, rule_name, cases, id=f"{module_name}:{rule_name}"
                )
            )
    return params


PARAMS = _params()


def test_corpus_present():
    # Guard against a missing/empty corpus dir making the suite vacuously pass.
    assert PARAMS, f"no corpus files found under {CORPUS_DIR}"


@pytest.mark.parametrize(("module_name", "rule_name", "cases"), PARAMS)
def test_corpus_round_trips(module_name: str, rule_name: str, cases: list[str]):
    module = importlib.import_module(f"abnf.grammars.{module_name}")
    rule = module.Rule(rule_name)
    for src in cases:
        node = rule.parse_all(src)
        assert node.value == src, (
            f"{module_name}:{rule_name} did not round-trip: {src!r} -> {node.value!r}"
        )
